### ISSUE TITLE
Encode []SDR в одну посылку CRCFail

### ISSUE THREAD

**Issue by vizzyolog** [egts/go-egts#2]
Я что-то не так делаю? Или этот функционал не поддерживается? 
Пытаюсь в ServicesFrameData добавить две записи ServiceDataRecord приемник такое отказывается принимать. 
Очень нужно. 
Может есть пример как реализовывать подобное? 

Спасибо!

**Comment by kuznetsovin** [comment]
Есть подозрение что пакет у вас не корректный так как если у вас CRCFail, то это ошибка контрольной суммы

**Comment by vizzyolog** [comment]
С множеством ServiceDataRecord вроде разобрался. 
Но, так и не могу отправить IMEI. Если делаю так -
```
var srTermIdentity   = egts.SrTermIdentity{
			TerminalIdentifier: 1234,
			MNE:                "0",
			BSE:                "0",
			NIDE:               "0",
			SSRA:               "0",
			LNGCE:              "0",
			IMSIE:              "0",
			IMEIE:              "0",
			HDIDE:              "0",
			IMEI: "000000000000000",
		}
```
Все норм пакет валидный. Reciver принимает.
Если ставлю флаг  IMEIE - ошибка. Может нужно сам IMEI не строкой отдавать?

**Comment by kuznetsovin** [comment]
Нужно смотреть спецификацию на предмет типа и длины IMEI

**Comment by vizzyolog** [comment]
Согласно спецификации длина IMEI 15 символов.

**Comment by kuznetsovin** [comment]
Если у вас есть конкретный пример пакета с IMEIE 1, и вы его предоставить, я смогу более точно ответить, в данный момент на пакетах, которые у меня есть ошибка не воспроизводится

**Comment by vizzyolog** [comment]
`var srTermIdentity   = egts.SrTermIdentity{
			TerminalIdentifier: 1234,
			MNE:                "0",
			BSE:                "0",
			NIDE:               "0",
			SSRA:               "0",
			LNGCE:              "0",
			IMSIE:              "0",
			IMEIE:              "1",
			HDIDE:              "0",
			HomeDispatcherIdentifier: 0,
			IMEI: "111111111111111",
			IMSI: "",
			LanguageCode: "",
			NetworkIdentifier: []byte{},
			BufferSize: 0,
			MobileNumber: "",
		}

	var egtsTermIdentity = egts.Package{
		ProtocolVersion:  1,
		SecurityKeyID:    0,
		Prefix:           "00",
		Route:            "0",
		EncryptionAlg:    "00",
		Compression:      "0",
		Priority:         "11",
		HeaderLength:     11,
		HeaderEncoding:   0,
		FrameDataLength:  19,
		PacketIdentifier: 0,
		PacketType:       1,
		ServicesFrameData: &egts.ServiceDataSet{
				egts.ServiceDataRecord{
				RecordLength:             8,
				RecordNumber:             95,
				SourceServiceOnDevice:    "1",
				RecipientServiceOnDevice: "0",
				Group:                    "0",
				RecordProcessingPriority: "11",
				TimeFieldExists:          "0",
				EventIDFieldExists:       "0",
				ObjectIDFieldExists:      "1",
				ObjectIdentifier:         2,
				SourceServiceType:        egts.AuthService,
				RecipientServiceType:     egts.AuthService,
				RecordDataSet: egts.RecordDataSet{
					egts.RecordData{
						SubrecordType: egts.SrTermIdentityType,
						SubrecordLength: 20,
						SubrecordData:  &srTermIdentity,
					},
				},
			},
		},
	}`

pkgIdent[1 0 3 11 0 19 0 0 0 1 198 8 0 95 0 153 2 0 0 0 1 1 1 20 0 210 4 0 0 2 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 41 176] 

2020-07-26T21:02:32.440573+03:00 egts_handler.go:85 DEBUG - Принят пакет: 0100030B001300000001C608005F0099020000000101011400D2040000023131

2020-07-26T21:02:32.440596+03:00 egts_handler.go:90 WARN - Ошибка расшифровки пакета
2020-07-26T21:02:32.440614+03:00 egts_handler.go:91 ERROR - Не удалось получить IMEI при авторизации
2020-07-26T21:02:32.440684+03:00 egts_handler.go:54 WARN - Пакет не соответствует формату ЕГТС. Закрыто соедиение 127.0.0.1:58625

**Comment by vizzyolog** [comment]
Разобрался. Ошибка в lenght'ах. 
Спасибо за package
